// Address
export const RARE24_CONTRACT_ADDRESS="0x432888D5fD5850A58A1BF2C7485115546F7A1f26"
export const MARKETPLACE_CONTRACT_ADDRESS=""

// ABI
export const RARE24_CONTRACT_ABI=[
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_treasury",
            "type":"address"
         },
         {
            "internalType":"string",
            "name":"uri_",
            "type":"string"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"constructor"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"sender",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"balance",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"needed",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"tokenId",
            "type":"uint256"
         }
      ],
      "name":"ERC1155InsufficientBalance",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"approver",
            "type":"address"
         }
      ],
      "name":"ERC1155InvalidApprover",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"idsLength",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"valuesLength",
            "type":"uint256"
         }
      ],
      "name":"ERC1155InvalidArrayLength",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"operator",
            "type":"address"
         }
      ],
      "name":"ERC1155InvalidOperator",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"receiver",
            "type":"address"
         }
      ],
      "name":"ERC1155InvalidReceiver",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"sender",
            "type":"address"
         }
      ],
      "name":"ERC1155InvalidSender",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"operator",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"owner",
            "type":"address"
         }
      ],
      "name":"ERC1155MissingApprovalForAll",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"Main__AlreadyMintedPhoto",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"Main__BatchLimitExceeded",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"Main__CannotWithdrawZeroFunds",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"Main__CoolDownStillActive",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"Main__CreatorPaymentFailed",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"Main__ExcessFundsForBatchMint",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"Main__ExcessiveFunds",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"Main__FeeTooHigh",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"Main__FeeTooLow",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"Main__InsufficientFunds",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"Main__InsufficientFundsForBatchMint",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"Main__InvalidMaxSupply",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"Main__InvalidPhotoPrice",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"Main__InvalidPlatformWallet",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"Main__MaxSupplyReached",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"Main__MintDurationExpired",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"Main__NotAuthorized",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"Main__NotPhotoCreator",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"Main__PhotoInactive",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"Main__RevenueWithdrawalFailed",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"Main__TooManyCollaborators",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"owner",
            "type":"address"
         }
      ],
      "name":"OwnableInvalidOwner",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"account",
            "type":"address"
         }
      ],
      "name":"OwnableUnauthorizedAccount",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"ReentrancyGuardReentrantCall",
      "type":"error"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"account",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"operator",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"bool",
            "name":"approved",
            "type":"bool"
         }
      ],
      "name":"ApprovalForAll",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"uint256",
            "name":"tokenId",
            "type":"uint256"
         },
         {
            "indexed":true,
            "internalType":"address[]",
            "name":"creators",
            "type":"address[]"
         },
         {
            "indexed":false,
            "internalType":"string",
            "name":"metadataURI",
            "type":"string"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"expiresAt",
            "type":"uint256"
         }
      ],
      "name":"Main__PhotoCreated",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"uint256",
            "name":"tokenId",
            "type":"uint256"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"creator",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint32",
            "name":"timestamp",
            "type":"uint32"
         }
      ],
      "name":"Main__PhotoDeactivated",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"uint256",
            "name":"tokenId",
            "type":"uint256"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"minter",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address[]",
            "name":"creators",
            "type":"address[]"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"editionNumber",
            "type":"uint256"
         }
      ],
      "name":"Main__PhotoMinted",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"uint256[]",
            "name":"tokenIds",
            "type":"uint256[]"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"minter",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint32",
            "name":"timestamp",
            "type":"uint32"
         }
      ],
      "name":"Main__PhotoMintedBatch",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"amount",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"uint32",
            "name":"timestamp",
            "type":"uint32"
         }
      ],
      "name":"Main__RevenueWithdrawn",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"newPlatformFee",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"uint32",
            "name":"timestamp",
            "type":"uint32"
         }
      ],
      "name":"Main__UpdatedPlatformFee",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":false,
            "internalType":"address",
            "name":"newPlatformWallet",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint32",
            "name":"timestamp",
            "type":"uint32"
         }
      ],
      "name":"Main__UpdatedPlatformWallet",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"previousOwner",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"newOwner",
            "type":"address"
         }
      ],
      "name":"OwnershipTransferred",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"operator",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"from",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"to",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256[]",
            "name":"ids",
            "type":"uint256[]"
         },
         {
            "indexed":false,
            "internalType":"uint256[]",
            "name":"values",
            "type":"uint256[]"
         }
      ],
      "name":"TransferBatch",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"operator",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"from",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"to",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"id",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"value",
            "type":"uint256"
         }
      ],
      "name":"TransferSingle",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":false,
            "internalType":"string",
            "name":"value",
            "type":"string"
         },
         {
            "indexed":true,
            "internalType":"uint256",
            "name":"id",
            "type":"uint256"
         }
      ],
      "name":"URI",
      "type":"event"
   },
   {
      "stateMutability":"payable",
      "type":"fallback"
   },
   {
      "inputs":[
         
      ],
      "name":"MAX_BATCH",
      "outputs":[
         {
            "internalType":"uint8",
            "name":"",
            "type":"uint8"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"creator",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"amount",
            "type":"uint256"
         }
      ],
      "name":"addToCreatorEarnings",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "name":"authorizedContracts",
      "outputs":[
         {
            "internalType":"bool",
            "name":"",
            "type":"bool"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"from",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"to",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"tokenId",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"amount",
            "type":"uint256"
         }
      ],
      "name":"authorizedSaleTransfer",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"account",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"id",
            "type":"uint256"
         }
      ],
      "name":"balanceOf",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address[]",
            "name":"accounts",
            "type":"address[]"
         },
         {
            "internalType":"uint256[]",
            "name":"ids",
            "type":"uint256[]"
         }
      ],
      "name":"balanceOfBatch",
      "outputs":[
         {
            "internalType":"uint256[]",
            "name":"",
            "type":"uint256[]"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256[]",
            "name":"tokenIds",
            "type":"uint256[]"
         }
      ],
      "name":"batchMintPhotos",
      "outputs":[
         
      ],
      "stateMutability":"payable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"tokenId",
            "type":"uint256"
         }
      ],
      "name":"deactivatePhoto",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"creator",
            "type":"address"
         }
      ],
      "name":"getCreatorAccruedFunds",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"creator",
            "type":"address"
         }
      ],
      "name":"getCreatorNextPost",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"creator",
            "type":"address"
         }
      ],
      "name":"getCreatorTokenIds",
      "outputs":[
         {
            "internalType":"uint256[]",
            "name":"",
            "type":"uint256[]"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"tokenId",
            "type":"uint256"
         }
      ],
      "name":"getPhotoDetails",
      "outputs":[
         {
            "components":[
               {
                  "internalType":"address[]",
                  "name":"creators",
                  "type":"address[]"
               },
               {
                  "internalType":"string",
                  "name":"metadataURI",
                  "type":"string"
               },
               {
                  "internalType":"uint256",
                  "name":"price",
                  "type":"uint256"
               },
               {
                  "internalType":"uint256",
                  "name":"createdAt",
                  "type":"uint256"
               },
               {
                  "internalType":"uint256",
                  "name":"expiresAt",
                  "type":"uint256"
               },
               {
                  "internalType":"uint256",
                  "name":"totalMinted",
                  "type":"uint256"
               },
               {
                  "internalType":"uint256",
                  "name":"maxSupply",
                  "type":"uint256"
               },
               {
                  "internalType":"bool",
                  "name":"active",
                  "type":"bool"
               }
            ],
            "internalType":"struct StructLibrary.Photo",
            "name":"",
            "type":"tuple"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"getPlatformFee",
      "outputs":[
         {
            "internalType":"uint8",
            "name":"",
            "type":"uint8"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"getPlatformRevenue",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"getTokenIdCounter",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"getTreasuryWallet",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"user",
            "type":"address"
         }
      ],
      "name":"getUserMintedTokenIds",
      "outputs":[
         {
            "internalType":"uint256[]",
            "name":"",
            "type":"uint256[]"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"account",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"operator",
            "type":"address"
         }
      ],
      "name":"isApprovedForAll",
      "outputs":[
         {
            "internalType":"bool",
            "name":"",
            "type":"bool"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"tokenId",
            "type":"uint256"
         }
      ],
      "name":"mintPhoto",
      "outputs":[
         
      ],
      "stateMutability":"payable",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"owner",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"renounceOwnership",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         },
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "name":"s_hasMinted",
      "outputs":[
         {
            "internalType":"bool",
            "name":"",
            "type":"bool"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "name":"s_tokenIdToPhotos",
      "outputs":[
         {
            "internalType":"string",
            "name":"metadataURI",
            "type":"string"
         },
         {
            "internalType":"uint256",
            "name":"price",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"createdAt",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"expiresAt",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"totalMinted",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"maxSupply",
            "type":"uint256"
         },
         {
            "internalType":"bool",
            "name":"active",
            "type":"bool"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"from",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"to",
            "type":"address"
         },
         {
            "internalType":"uint256[]",
            "name":"ids",
            "type":"uint256[]"
         },
         {
            "internalType":"uint256[]",
            "name":"values",
            "type":"uint256[]"
         },
         {
            "internalType":"bytes",
            "name":"data",
            "type":"bytes"
         }
      ],
      "name":"safeBatchTransferFrom",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"from",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"to",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"id",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"value",
            "type":"uint256"
         },
         {
            "internalType":"bytes",
            "name":"data",
            "type":"bytes"
         }
      ],
      "name":"safeTransferFrom",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"operator",
            "type":"address"
         },
         {
            "internalType":"bool",
            "name":"approved",
            "type":"bool"
         }
      ],
      "name":"setApprovalForAll",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_contract",
            "type":"address"
         },
         {
            "internalType":"bool",
            "name":"_authorized",
            "type":"bool"
         }
      ],
      "name":"setAuthorizedContract",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint8",
            "name":"newFee",
            "type":"uint8"
         }
      ],
      "name":"setPlatformFee",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"newWallet",
            "type":"address"
         }
      ],
      "name":"setTreasurytWallet",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"bytes4",
            "name":"interfaceId",
            "type":"bytes4"
         }
      ],
      "name":"supportsInterface",
      "outputs":[
         {
            "internalType":"bool",
            "name":"",
            "type":"bool"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"newOwner",
            "type":"address"
         }
      ],
      "name":"transferOwnership",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"treasury",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"string",
            "name":"metadataURI",
            "type":"string"
         },
         {
            "internalType":"uint256",
            "name":"price",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"maxSupply",
            "type":"uint256"
         },
         {
            "internalType":"address[]",
            "name":"creators",
            "type":"address[]"
         }
      ],
      "name":"uploadNft",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"tokenId",
            "type":"uint256"
         }
      ],
      "name":"uri",
      "outputs":[
         {
            "internalType":"string",
            "name":"",
            "type":"string"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"amount",
            "type":"uint256"
         }
      ],
      "name":"withdrawPlatformRevenue",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "stateMutability":"payable",
      "type":"receive"
   }
]
export const MARKETPLACE_CONTRACT_ABI=[]